config = {"app_name": "Jake's Christmas Quiz",
          "theme": "christmas"}

questions = [{"question": "In which country does Santa have his own personal postcode HOH OHO?",
              "answers": ["Canada", "USA", "France", "Russia"],
              "correct_answer": 0,
              "points": 10,
              },
              {"question": "What Christmas Advert contains this song?",
               "audio": "static/questions/tgg.mp3",
               "answers": ["Lidl", "Sainsbury's", "Asda", "John Lewis"],
               "correct_answer": 1,
               "points": 20
              },
              {"question": "Which country dontates a christmas tree to the UK to be displayed in Trafalgar Sqaure",
              "answers": ["Sweden", "Finland", "Russia", "Norway"],
              "correct_answer": 3,
              "points": 10,
              },
              {"question": "Which Apollo mission spent Christmas Day 1968 circling the moon?",
              "answers": ["Apollo 7", "Apollo 8", "Apollo 9", "Apollo 11"],
              "correct_answer": 1,
              "points": 20,
              },
              {"question": "What was the name of the penguin in the 2014 John Lewis Christmas Advert?",
              "answers": ["Boxer", "Percy", "Perry", "Monty"],
              "correct_answer": 3,
              "points": 10,
              },
              {"question": "Where did the real St. Nicholas live?",
              "answers": ["North Pole", "Holland", "Turkey", "Germany"],
              "correct_answer": 2,
              "points": 25,
              },
              {"question": "When are the '12 Days of Christmas'?",
              "answers": ["December 21 to January 1", "December 26 to January 6", "Christmas Eve to January 4", "December 14 to December 25"],
              "correct_answer": 1,
              "points": 15,
              },
              {"question": "The Queen's Speech was first shown on TV in which year?",
              "answers": ["1954", "1956", "1957", "1961"],
              "correct_answer": 2,
              "points": 20,
              },
              {"question": "Which king influenced the change from goose to turkey as the traditional meat to be served on Christmas Day?",
              "answers": ["Charles I", "Charles II", "Richard II", "Henry VIII"],
              "correct_answer": 3,
              "points": 10,
              },
              {"question": "What day is Christmas on this year?",
              "answers": ["Sunday", "Friday", "Monday", "Saturday"],
              "correct_answer": 0,
              "points": 10,
              },
              {"question": "On what means of communication was 'Merry Christmas' the first message sent?",
              "answers": ["E-mail", "SMS", "Internet", "Mourse Code"],
              "correct_answer": 1,
              "points": 15,
              },
              {"question": "In the Simpsons, what is named \"Santa's little helper\"",
              "answers": ["A pet fish", "A pet cat", "A pet monkey", "A pet dog"],
              "correct_answer": 3,
              "points": 10,
              },
              {"question": "In which ocean does Christmas Island lie?",
              "answers": ["Pacific Ocean", "Indian Ocean", "Atlantic Ocean", "Arctic Ocean"],
              "correct_answer": 1,
              "points": 20,
              },
              {"question": "Who is Rudolph's mother?",
              "answers": ["Blitzen", "Comet", "Donner", "Vixen"],
              "correct_answer": 2,
              "points": 25,
              },
              {"question": "What were Frosty the Snowman's eyes made out of?",
              "answers": ["Coal", "Stones", "Bottle Caps", "Pebbles"],
              "correct_answer": 0,
              "points": 15,
              }
]
